implementation/LiYancong/2019-07-23/Wit2Wit/Wit2Wit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'Wit2Wit.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^user/', include('user.urls', namespace='user')),  # 用户
    url(r'^cart/', include('cart.urls', namespace='cart')),  # 购物车
    url(r'^order/', include('order.urls', namespace='order')),  # 订单
    url(r'^query', include('haystack.urls')),  # 全文检索框架
    url(r'^', include('goods.urls', namespace='goods')),  # 商品，因作为首页，所以url地址未填内容
]

implementation/LiYancong/2019-07-23/Wit2Wit/apps/cart/urls.py
from django.conf.urls import url
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^addcart$', CartAddView.as_view(), name='addcart'),  # 购物车记录添加
    url(r'^$', CartInfoView.as_view(), name='cartinfo'),  # 购物车页面显示
    url(r'^updatecart$', CartUpdateView.as_view(), name='updatecart'),  # 购物车记录更新
    url(r'^deletecart$', CartDeleteView.as_view(), name='deletecart'),  # 购物车记录删除
]

implementation/LiYancong/2019-07-23/Wit2Wit/apps/goods/urls.py
from django.conf.urls import url
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
    url(r'^index/$', IndexView.as_view(), name='index'),  # 首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
    url(r'^$', IndexView.as_view(), name='index2'),  # 首页
]

implementation/LiYancong/2019-07-23/Wit2Wit/apps/order/urls.py
from django.conf.urls import url
from order.views import OrderPageView, OrderSubmitView

urlpatterns = [
    url(r'^confirm_order$', OrderPageView.as_view(), name='confirm_order'), # 提交订单页面显示
    url(r'^submit_order$', OrderSubmitView.as_view(), name='submit_order'), # 创建一个订单
]

implementation/LiYancong/2019-07-23/Wit2Wit/apps/user/urls.py
from django.conf.urls import url
from user.views import RegisterView, SendMessageView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView

urlpatterns = [
    url(r'^register$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^send_message$', SendMessageView.as_view(), name='send_message'),  # 发送短信验证码
    url(r'^login$', LoginView.as_view(), name='login'),  # 登录
    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 退出登录

    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # 用户订单页
    url(r'^address$', AddressView.as_view(), name='address'),  # 用户地址页
    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户信息页
]

implementation/LiYancong/2019-07-23/Wit2Wit/apps/cart/models.py
from django.db import models

# Create your models here.

implementation/LiYancong/2019-07-23/Wit2Wit/apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel
from tinymce.models import HTMLField


# Create your models here.


class User(AbstractUser, BaseModel):
    '''用户模型类'''
    USER_TYPE_CHOICES = (
        (1, '学习者'),
        (2, '授业者'),
        (3, '管理员')
    )

    nick_name = models.CharField(max_length=50, verbose_name="昵称", default="")
    birthday = models.DateField(verbose_name="生日", blank=True, null=True)
    mobile = models.CharField(max_length=11, verbose_name="手机", default="")
    addr = models.CharField(max_length=50, verbose_name="地址", default="")  # 这里是小地址，比如“北京市海淀区”
    image = models.ImageField(verbose_name="用户头像", upload_to="users/%Y/%m", default="")
    user_type = models.SmallIntegerField(choices=USER_TYPE_CHOICES, default=1, verbose_name='用户类型')

    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name


class AddressManager(models.Manager):
    '''地址模型管理器类'''

    def get_default_address(self, user):
        '''获取用户默认的收货地址'''
        try:
            address = self.get(user=user, is_default=True)
        except self.model.DoesNotExist:
            address = None

        return address


class Address(BaseModel):
    '''地址模型类'''
    user = models.ForeignKey('User', verbose_name='所属账户')
    receiver = models.CharField(max_length=20, verbose_name='收件人')
    addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')

    # 自定义一个模型管理器对象
    objects = AddressManager()

    class Meta:
        db_table = 'df_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name


class Teacher(BaseModel):
    '''教师用户表'''
    user = models.ForeignKey('User', verbose_name='所属用户')
    name = models.CharField(max_length=50, verbose_name='姓名')
    intro = HTMLField(blank=True, verbose_name='教师简介')
    is_active = models.BooleanField(default=True, verbose_name='是否激活')

    class Meta:
        db_table = 'df_teacher'
        verbose_name = '授业者'
        verbose_name_plural = verbose_name

implementation/LiYancong/2019-07-23/Wit2Wit/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.UserUtil import LoginRequiredMixin


# Create your views here.
# /cart/addcart
class CartAddView(View):
    '''购物车记录添加'''

    def post(self, request):
        '''购物车记录添加'''
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'status': -1, 'msg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'status': -1, 'msg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'status': -1, 'msg': '请输入正确的商品数量'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'status': -1, 'msg': '该商品不存在'})

        # 业务处理:添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值 -> hget(name, key)
        # 如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 累加购物车中商品的数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'status': -1, 'msg': '该商品库存不足'})

        # 设置hash中sku_id对应的值
        # hset->如果sku_id已经存在，更新数据， 如果sku_id不存在，添加数据
        # hset(name, key, value)
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'status': 1, 'cart_count': total_count, 'msg': '添加成功'})


# /cart/
class CartInfoView(LoginRequiredMixin, View):
    '''购物车页面显示'''

    def get(self, request):
        '''显示'''
        # 获取登录的用户
        user = request.user
        # 获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # {'商品id':商品数量, ...}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保存用户购物车中商品的总数目和总价格
        cart_count = 0
        cart_price = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)
            # 动态给sku对象增加一个属性amount, 保存商品的小计
            sku.amount = amount
            # 动态给sku对象增加一个属性count, 保存购物车中对应商品的数量
            sku.count = count
            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            cart_count += int(count)
            cart_price += amount

        # 组织上下文
        context = {'skus': skus,
                   'cart_count': cart_count,
                   'cart_price': cart_price
                   }

        # 使用模板
        return render(request, 'cart.html', context)


# 更新购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品id(sku_id) 更新的商品数量(count)
# /cart/updatecart
class CartUpdateView(View):
    '''购物车记录更新'''

    def post(self, request):
        '''购物车记录更新'''
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'status': -1, 'msg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'status': -1, 'msg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'status': -1, 'msg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'status': -1, 'msg': '商品不存在'})

        # 业务处理:更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'status': -1, 'msg': '商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'status': 1, 'cart_count': total_count, 'msg': '购物车更新成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品的id(sku_id)
# /cart/deletecart
class CartDeleteView(View):
    '''购物车记录删除'''

    def post(self, request):
        '''购物车记录删除'''
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'status': -1, 'msg': '请先登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据的校验
        if not sku_id:
            return JsonResponse({'status': -1, 'msg': '无效的商品'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'status': -1, 'msg': '商品不存在'})

        # 业务处理:删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'status': 1, 'cart_count': total_count, 'msg': '商品删除成功'})

implementation/LiYancong/2019-07-23/Wit2Wit/apps/order/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from utils.UserUtil import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django_redis import get_redis_connection
from user.models import Address
from goods.models import GoodsSKU
from django.db import transaction
from django.http import JsonResponse
from order.models import OrderInfo, OrderGoods
from datetime import datetime


# Create your views here.

# /order/confirm_order
class OrderPageView(LoginRequiredMixin, View):
    '''提交订单页面显示'''

    def post(self, request):
        user = request.user
        sku_ids = request.POST.getlist('sku_ids')  # 从前台提交过来的name为sku_ids的数据，里边存放了所有被选中的商品id，为列表形式

        # 看看传过来的id对不对，如果不对，就跳转到购物车页面
        if not sku_ids:
            return redirect(reverse('cart:cartinfo'))

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        skus = []
        # 保存商品的总件数和总价格
        total_count = 0
        total_price = 0
        # 遍历sku_ids获取用户要购买的商品的信息
        for sku_id in sku_ids:
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 获取用户所要购买的商品的数量
            count = conn.hget(cart_key, sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)
            # 动态给sku增加属性count,保存购买商品的数量
            sku.count = count
            # 动态给sku增加属性amount,保存购买商品的小计
            sku.amount = amount
            # 追加
            skus.append(sku)
            # 累加计算商品的总件数和总价格
            total_count += int(count)
            total_price += amount

        # 运费
        postage = 0  # 写死

        # 实付款
        total_pay = total_price + postage

        # 获取用户的收件地址
        addrs = Address.objects.filter(user=user)

        # 组织上下文
        sku_ids = ','.join(sku_ids)  # [1,25]->1,25
        context = {'skus': skus,
                   'cart_count': total_count,
                   'cart_price': total_price,
                   'postage': postage,
                   'total_price': total_pay,
                   'addrs': addrs,
                   'sku_ids': sku_ids}

        # 使用模板
        return render(request, 'order.html', context)


# /order/submit_order
class OrderSubmitView(View):
    '''创建一个新的订单'''

    @transaction.atomic
    def post(self, request):
        # 判断用户是否登录
        user = request.user
        if not user.is_authenticated():
            # 用户未登录
            return JsonResponse({'status': -1, 'msg': '用户未登录'})  # 返回-1的话，需要跳转，所以要和其他的status值区别开

        # 接收参数
        addr_id = request.POST.get('addr_id')
        pay_method = request.POST.get('pay_method')
        teaching_mode = request.POST.get('teaching_mode')
        sku_ids = request.POST.get('sku_ids')  # 1,2,3

        # 校验参数
        if not all([addr_id, pay_method, teaching_mode, sku_ids]):
            return JsonResponse({'status': 0, 'msg': '参数不完整'})

        # 校验支付方式
        if pay_method not in OrderInfo.PAY_METHODS.keys():
            return JsonResponse({'status': 0, 'msg': '无效的支付方式'})

            # 校验地址
        try:
            addr = Address.objects.get(id=addr_id)
        except Address.DoesNotExist:
            # 地址不存在
            return JsonResponse({'status': 0, 'msg': '无效的授业地址'})
        # 开始创建订单

        # 组织参数
        # 订单id: 当前时间+用户id
        # order_id = str(time.time(), 2).replace('.', '') + str(user.id)
        order_id = datetime.now().strftime('%Y%m%d%H%M%S') + str(user.id)

        # 运费
        postage = 0

        # 总数目和总金额
        total_count = 0
        total_price = 0

        # 设置事务保存点
        save_id = transaction.savepoint()
        try:
            # 向df_order_info表中添加一条记录
            order = OrderInfo.objects.create(order_id=order_id,
                                             user=user,
                                             addr=addr,
                                             pay_method=pay_method,
                                             teaching_mode=teaching_mode,
                                             total_count=total_count,
                                             total_price=total_price,
                                             transit_price=postage)

            # 用户的订单中有几个商品，需要向df_order_goods表中加入几条记录
            conn = get_redis_connection('default')
            cart_key = 'cart_%d' % user.id

            sku_ids = sku_ids.split(',')
            for sku_id in sku_ids:
                for i in range(3):
                    # 获取商品的信息
                    try:
                        sku = GoodsSKU.objects.get(id=sku_id)
                    except:
                        # 商品不存在
                        transaction.savepoint_rollback(save_id)
                        return JsonResponse({'status': 0, 'msg': '商品不存在'})

                    # 从redis中获取用户所要购买的商品的数量
                    count = conn.hget(cart_key, sku_id)

                    # 判断商品的库存
                    if int(count) > sku.stock:
                        transaction.savepoint_rollback(save_id)
                        return JsonResponse({'status': 0, 'msg': '商品库存不足'})

                    # 更新商品的库存和销量
                    orgin_stock = sku.stock
                    new_stock = orgin_stock - int(count)
                    new_sales = sku.sales + int(count)

                    # 返回受影响的行数
                    # 在这里用了简单的乐观锁，不过只是判断了库存是不是和之前一致，如果项目说不要有库存这个东西啦，那么我们就判断销量好了
                    res = GoodsSKU.objects.filter(id=sku_id, stock=orgin_stock).update(stock=new_stock, sales=new_sales)
                    if res == 0:
                        if i == 2:
                            # 尝试的第3次
                            transaction.savepoint_rollback(save_id)
                            return JsonResponse({'status': 0, 'msg': '下单失败'})
                        continue

                    # 向df_order_goods表中添加一条记录
                    OrderGoods.objects.create(order=order,
                                              sku=sku,
                                              count=count,
                                              price=sku.price)

                    # 累加计算订单商品的总数量和总价格
                    amount = sku.price * int(count)
                    total_count += int(count)
                    total_price += amount

                    # 跳出循环
                    break

            # 更新订单信息表中的商品的总数量和总价格
            order.total_count = total_count
            order.total_price = total_price
            order.save()
        except Exception as e:
            transaction.savepoint_rollback(save_id)
            return JsonResponse({'status': 0, 'msg': '下单失败'})

        # 提交事务
        transaction.savepoint_commit(save_id)

        # 清除用户购物车中对应的记录,因为sku_ids是列表，所以用*拆开
        conn.hdel(cart_key, *sku_ids)

        # 返回应答
        return JsonResponse({'status': 1, 'msg': '下单成功'})

implementation/LiYancong/2019-07-23/Wit2Wit/templates/index_copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    {% if user.is_authenticated %}
        <div>
            欢迎您：{{ user.username }}
            <a href="{% url 'user:logout' %}">退出</a>
			<label>您的<a href="{% url 'cart:cartinfo' %}">购物车</a>中有{{cart_count}}件商品</label>
        </div>
    {% else %}
        <div>
            <a href="{% url 'user:login' %}">登录</a>
            <a href="{% url 'user:register' %}">注册</a>
        </div>
    {% endif %}
    <hr/>
	<p>这里我放上了搜索框</p>
	<form method="get" action="/query">
		<input type="text" name="q" placeholder="搜索商品">
		<input type="submit" name="" value="搜索">
	</form>
	<hr/>
    <div>
		<ul>
            {% for type in types %}
			    <li><a href="#category0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div>
            {% for banner in goods_banners  %}
                <ul>
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="轮播图"></a></li>
                </ul>
            {% endfor %}
		</div>
		<div>
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div>
		<div>
			<h3 id="category0{{ forloop.counter }}">{{ type.name }}</h3>
			<div>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" id="view_more">查看更多 ></a>
		</div>
		<div>
			<div><img src="{{ type.image.url }}"></div>
			<ul>
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div>¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
</body>
</html>

implementation/LiYancong/2019-07-23/Wit2Wit/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
</head>
<body>
<div>
    <div>
        <a href="{% url 'goods:list' type.id 1 %}">默认</a>
        <a href="{% url 'goods:list' type.id 1 %}?sort=price_asc">价格↑</a>
        <a href="{% url 'goods:list' type.id 1 %}?sort=price_desc">价格↓</a>
        <a href="{% url 'goods:list' type.id 1 %}?sort=sales">销量</a>
    </div>

    <ul>
        {% for sku in skus_page %}
        <li>
            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
            <p><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></p>
            <div>
                <span>价格：￥{{ sku.price }}</span>
                <span>规格：{{ sku.price}}/{{ sku.unite }}</span>
                <a href="#" title="加入购物车"></a>
            </div>
        </li>
        {% endfor %}
    </ul>

    <div>
        {% if skus_page.has_previous %}
        <a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">
            上一页
        </a>
        {% endif %}
        {% for pindex in pages %}
        {% if pindex == skus_page.number %}
        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" style="font-size:30px">{{ pindex }}</a>
        {% else %}
        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
        {% endif %}
        {% endfor %}
        {% if skus_page.has_next %}
        <a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页</a>
        {% endif %}
    </div>
</div>
</body>
</html>

implementation/LiYancong/2019-07-23/Wit2Wit/templates/static_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    {% if user.is_authenticated %}
        <div>
            欢迎您：{{ user.username }}
            <a href="{% url 'user:logout' %}">退出</a>
        </div>
    {% else %}
        <div>
            <a href="{% url 'user:login' %}">登录</a>
            <a href="{% url 'user:register' %}">注册</a>
        </div>
    {% endif %}
    <hr/>
    <div>
		<ul>
            {% for type in types %}
			    <li><a href="#category0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div>
            {% for banner in goods_banners  %}
                <ul>
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="轮播图"></a></li>
                </ul>
            {% endfor %}
		</div>
		<div>
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div>
		<div>
			<h3 id="category0{{ forloop.counter }}">{{ type.name }}</h3>
			<div>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" id="view_more">查看更多 ></a>
		</div>
		<div>
			<div><img src="{{ type.image.url }}"></div>
			<ul>
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div>¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
</body>
</html>

implementation/LiYancong/2019-07-23/Wit2Wit/templates/user_center.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/user.js' %}"></script>
</head>
<body>

<div>
    <div>
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'user:user' %}">个人信息</a></li>
            <li><a href="{% url 'user:order' 1 %}">全部订单</a></li>
            <li><a href="{% url 'user:address' %}">收货地址</a></li>
        </ul>
    </div>
    假设这是右侧区域
    <hr/>
    假设这里放用户信息
    <div>
        <ul>
            <li><span>用户名：</span>{{ user.username }}</li>
            <li><span>联系方式：</span>{{ user.mobile }}</li>
        </ul>
    </div>
    <hr/>
    假设这里放收货地址
    <form method="post" action="address">
        {% csrf_token %}
        <div>
            {% if address_list %}
            {% for address in address_list %}
            <p>地址：{{ address.addr }} （{{ address.receiver }} 收） 电话：{{ address.phone }} 邮编：{{ address.zip_code }}
                {{address.is_default}} <input
                        type="button" onclick="delete_address({{ address.id }})" value="删除地址"/><input
                        type="button" onclick="default_address({{ address.id }})" value="设为默认地址"/><input
                        type="button" onclick="update_address({{ address.id }})" value="修改地址"/>
            </p>

            {% endfor %}
            {% else %}
            无默认地址
            {% endif %}
        </div>
    </form>
    <hr/>
    假设这里可以添加收货地址
    <div>
        <form method="post" action="address">
            {% csrf_token %}
            <div>
                <label>收件人：</label>
                <input type="text" id="receiver" name="receiver">
            </div>
            <div>
                <label>详细地址：</label>
                <textarea id="addr" name="addr"></textarea>
            </div>
            <div>
                <label>邮编：</label>
                <input type="text" id="zip_code" name="zip_code">
            </div>
            <div>
                <label>手机：</label>
                <input type="text" id="phone" name="phone">
            </div>
            <input type="hidden" id="mode" name="mode" value="1">
            <input type="submit" value="提交">
        </form>
    </div>
</div>
</body>
</html>